export const walkdownList = [
  {
    id: 10,
    title: 'Walkdown #10',
    description: 'Safety & Compliance Inspection',
    assets: 13,
    date: '18 May 2025',
    icon: 'clipboard-check-outline',
    iconFamily: 'MaterialCommunityIcons',
    iconBackground: '#EAF4FF',
    iconColor: '#1677FF',
    badgeBackground: '#EAF4FF',
    badgeColor: '#1677FF',
  },
  {
    id: 11,
    title: 'Walkdown #11',
    description: 'Walkdown Findings Consolidation',
    assets: 6,
    date: '16 May 2025',
    icon: 'clipboard-check-outline',
    iconFamily: 'MaterialCommunityIcons',
    iconBackground: '#EAF9F0',
    iconColor: '#16A34A',
    badgeBackground: '#EAF9F0',
    badgeColor: '#16A34A',
  },
  {
    id: 12,
    title: 'Walkdown #12',
    description: 'Test',
    assets: 3,
    date: '14 May 2025',
    icon: 'clipboard-check-outline',
    iconFamily: 'MaterialCommunityIcons',
    iconBackground: '#F3E8FF',
    iconColor: '#7C3AED',
    badgeBackground: '#F3E8FF',
    badgeColor: '#7C3AED',
  },
  {
    id: 13,
    title: 'Walkdown #16',
    description: 'Site Safety Verification',
    assets: 2,
    date: '12 May 2025',
    icon: 'clipboard-check-outline',
    iconFamily: 'MaterialCommunityIcons',
    iconBackground: '#FFF7E6',
    iconColor: '#F59E0B',
    badgeBackground: '#FFF7E6',
    badgeColor: '#F59E0B',
  },
   {
    id: 14,
    title: 'Walkdown #12',
    description: 'Test',
    assets: 3,
    date: '14 May 2025',
    icon: 'clipboard-check-outline',
    iconFamily: 'MaterialCommunityIcons',
    iconBackground: '#F3E8FF',
    iconColor: '#7C3AED',
    badgeBackground: '#F3E8FF',
    badgeColor: '#7C3AED',
  },
  {
    id: 15,
    title: 'Walkdown #16',
    description: 'Site Safety Verification',
    assets: 2,
    date: '12 May 2025',
    icon: 'clipboard-check-outline',
    iconFamily: 'MaterialCommunityIcons',
    iconBackground: '#FFF7E6',
    iconColor: '#F59E0B',
    badgeBackground: '#FFF7E6',
    badgeColor: '#F59E0B',
  },
   {
    id: 16,
    title: 'Walkdown #12',
    description: 'Test',
    assets: 3,
    date: '14 May 2025',
    icon: 'clipboard-check-outline',
    iconFamily: 'MaterialCommunityIcons',
    iconBackground: '#F3E8FF',
    iconColor: '#7C3AED',
    badgeBackground: '#F3E8FF',
    badgeColor: '#7C3AED',
  },
  {
    id: 17,
    title: 'Walkdown #16',
    description: 'Site Safety Verification',
    assets: 2,
    date: '12 May 2025',
    icon: 'clipboard-check-outline',
    iconFamily: 'MaterialCommunityIcons',
    iconBackground: '#FFF7E6',
    iconColor: '#F59E0B',
    badgeBackground: '#FFF7E6',
    badgeColor: '#F59E0B',
  },
];